### ISSUE TITLE
Crashes with current dump

### ISSUE THREAD

**Issue by p-sodmann** [Liebeck/IWNLP#26]
The Parser crashes if I try to parse a current dump of wiktionary.

Full output:

PronounParser: contains parenthesis welcher

PronounParser: contains parenthesis welcher

PronounParser: contains parenthesis welcher

PronounParser: contains parenthesis welcher

NounParser: contains parenthesis: Zeche

VerbSchwachUntrennbarParser: Flexion:sperbern parsing arguments, possible empty parameter

Error Verb Flexparser: Flexion:wohltun, wohltue<br />ich tu

AdjectiveFlexParser: No definition block: Flexion:heben/Gerundivum

Unbehandelte Ausnahme: System.InvalidOperationException: Die Sequenz enthält keine Elemente.

   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

   bei IWNLP.Parser.FlexParser.VerbFlexParser.Parse(String word, String[] text) in C:\works\tools\iwnlp\IWNLP\IWNLP.Parser\FlexParser\VerbFlexParser.cs:Zeile 28.

   bei IWNLP.Parser.WiktionaryParser.ParseText(String word, String textInput, Int32 wikiID) in C:\works\tools\iwnlp\IWNLP\IWNLP.Parser\WiktionaryParser.cs:Zeile 95.

   bei IWNLP.Parser.Program.Main(String[] args) in C:\works\tools\iwnlp\IWNLP\IWNLP.Parser\Program.cs:Zeile 50.

**Comment by Liebeck** [comment]
I added some exception handling to prevent further crashes. With the current dump, there are 3 unit tests failing but I don't have time to fix them right now. Pull requests are welcome ;-)

**Comment by p-sodmann** [comment]
Thank you for fixing the bug.
